### ISSUE TITLE
relay-hooks v2.1.0

### ISSUE THREAD

**Issue by morrys** [relay-tools/relay-hooks#49]
branch: https://github.com/relay-tools/relay-hooks/tree/48-typing-mutations

* [X] fix mutation typing https://github.com/relay-tools/relay-hooks/issues/48
* [X] fix useOssFragment, useFragment, useRefetch & usePagination typing https://github.com/relay-tools/relay-hooks/issues/41
* [x] Add fetchKey property in useQuery https://github.com/relay-tools/relay-hooks/issues/47
* [X] added nextjs - ssr typescript example https://github.com/relay-tools/relay-hooks/commit/353cc030821b50a873e78f279ca47fbc41e1b177 https://github.com/relay-tools/relay-hooks/issues/21

**Comment by morrys** [comment]
Hi @akomm,
soon I should release the new version of relay-hooks that improves typing :)

**Comment by akomm** [comment]
Thanks for the great work :)

**Comment by morrys** [comment]
I plan to release the library this weekend

**Comment by akomm** [comment]
I see refs now also have a branded type instead of any :)

**Comment by jazblueful** [comment]
There is also new version of Relay available

**Comment by morrys** [comment]
Hi to all,
today I released version 2.1.0!
https://github.com/relay-tools/relay-hooks/releases/tag/v2.1.0

@jazblueful as for relay v8.0.0 support, I have opened a new issue:
https://github.com/relay-tools/relay-hooks/issues/52

**Comment by jazblueful** [comment]
@morrys Thank you!
